name: Build rate_limiter.so

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Cython
        run: |
          python -m pip install --upgrade pip
          pip install cython setuptools

      - name: Build rate_limiter.so
        run: |
          python setup.py build_ext --inplace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rate_limiter-so
          path: rate_limiter*.so
